Repository statisticswithoutborders/swb-app, pull requests merged in 2020-09, with the labels that each got.

#163 VolunteersPage (issue #52)
  client/src/pages/VolunteersPage/VolunteersPage.css
  client/src/pages/VolunteersPage/VolunteersPage.js
Labels: awaiting review

#164 Feature ContactUsPage test - twc
  client/src/App.js
  client/src/pages/ContactUsPage/ContactUsPage.css
  client/src/pages/ContactUsPage/ContactUsPage.js
  client/src/pages/ContactUsPage/ContactUsPage.test.js
Labels: awaiting review

#174 Add links to AboutUs page #137
  client/src/App.css
  client/src/App.js
  client/src/components/MemberCard/MemberCard.js
Labels: awaiting review

#176 ProjectPage Quality Control Update issue#168
  client/src/components/ProjectImageGallery/ProjectImageGallery.css
  client/src/components/ProjectPage/ProjectPage.css
  client/src/components/ProjectPage/ProjectPageAsante.js
  client/src/components/ProjectPage/ProjectPageChimp.js
  client/src/components/ProjectPage/ProjectPageEthiopia.js
  client/src/components/ProjectPage/ProjectPageHaiti.js
  client/src/components/ProjectPage/ProjectPageSyria.js
  client/src/components/ProjectPage/ProjectPageUnicef.js
Labels: awaiting review

#161 Feature BlogCard test twc
  client/src/components/BlogCard/BlogCard.js
  client/src/components/BlogCard/BlogCard.test.js
Labels: awaiting review

#175 HowItWorks QC update (issues #169, #171, #172)
  client/src/components/HowItWorks/HowItWorks.css
Labels: awaiting review

#173 volunteersPage QC Update (issue #170)
  client/src/pages/VolunteersPage/VolunteersPage.css
  client/src/pages/VolunteersPage/VolunteersPage.js
Labels: awaiting review

#124 line on top of footer merge conflict served
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.js
Labels: Atomic Component

#151 IconDownArrow - Test
  client/src/components/IconDownArrow/IconDownArrow.test.js
Labels: Testing

#179 Card width bug (issue #117)
  client/src/components/Card/Card.css
  client/src/components/Card/Card.js
  client/src/components/Card/Card.stories.js
  client/src/components/HowItWorks/HowItWorks.css
  client/src/pages/VolunteersPage/VolunteersPage.css
  client/src/pages/VolunteersPage/VolunteersPage.js
Labels: awaiting review

#183 FormContact-qc-twc
  client/src/components/FormContact/FormContact.css
Labels: awaiting review

#181 Feature-Input-qc-twc
  client/src/components/Input/Input.js
  client/src/components/Input/Input.stories.js
Labels: awaiting review

#180 fixed blog-model
  api/swb/admin.py
  api/swb/migrations/0012_blog.py
  api/swb/models.py
Labels: awaiting review

#185 testimonials - added media queries for tablets and phones
  client/src/components/Testimonial/Testimonial.css
Labels: Quality Control, awaiting review

#190 OurServicesPage-FormContact-qc-twc
  client/src/components/FormContact/FormContact.css
  client/src/components/Input/Input.css
  client/src/pages/ContactUsPage/ContactUsPage.css
  client/src/pages/OurServicesPage/OurServicesPage.css
  client/src/pages/OurServicesPage/OurServicesPage.js
Labels: awaiting review

#186 Add Form to Home
  client/src/App.css
  client/src/App.js
  client/src/components/Card/Card.css
  client/src/components/WhoWeAreCard/WhoWeAreCard.css
  client/src/pages/Home/Home.css
  client/src/pages/Home/Home.js
Labels: Quality Control, awaiting review

#195 Member serializer and Project Model fix backend issue#193
  api/settings.sql
  api/swb/fixtures/swb.json
  api/swb/migrations/0013_remove_project_project_tag.py
  api/swb/models.py
  api/swb/serializers.py
  api/swb/urls.py
  api/swb/views.py
Labels: awaiting review

#189 Aboutus
  client/src/components/FundingFact/FundingFact.css
  client/src/components/IconArrow/IconArrow.css
  client/src/components/IconNumber/IconNumber.css
  client/src/components/MemberCard/MemberCard.css
  client/src/components/Objective/Objective.css
  client/src/pages/AboutUsPage/AboutUsPage.css
  client/src/pages/AboutUsPage/AboutUsPage.js
Labels: awaiting review

#205 OurMission/Banner QC
  client/src/pages/Home/Home.css
Labels: Quality Control, awaiting review

#200 Form serializers/views/urls
  api/api/__pycache__/settings.cpython-38.pyc
  api/settings.sql
  api/swb/serializers.py
  api/swb/urls.py
  api/swb/views.py
Labels: awaiting review

#206 Home 100% width > screen size #198
  client/src/pages/Home/Home.css
Labels: Quality Control, awaiting review

#184 Added links to navbar and some responsiveness
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/assets/images/icons8-menu.svg
  client/src/components/HamburgerMenu/HamburgerMenu.css
  client/src/components/HamburgerMenu/HamburgerMenu.js
  client/src/components/HamburgerMenu/HamburgerMenu.stories.js
  client/src/components/HamburgerMenu/HamburgerMenu.test.js
  client/src/components/NavBar/NavBar.css
  client/src/components/NavBar/NavBar.js
Labels: awaiting review

#202 Feature footer hr color twc
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.js
  client/src/components/Footer/Footer.stories.js
Labels: awaiting review

#215 Navbar spacing (issue #208)
  client/src/components/NavBar/NavBar.css
  client/src/components/NavBar/NavBar.js
Labels: awaiting review

#219 OurServicesPage - Video Section
  client/src/pages/OurServicesPage/OurServicesPage.css
  client/src/pages/OurServicesPage/OurServicesPage.js
Labels: awaiting review

#216 AboutUs page overflow
  client/src/pages/AboutUsPage/AboutUsPage.css
Labels: awaiting review

#221 FormContact-responsive-twc
  client/src/components/FormContact/FormContact.js
  client/src/components/Input/Input.css
  client/src/pages/ContactUsPage/ContactUsPage.js
  client/src/pages/Home/Home.js
Labels: awaiting review

#210 FundingFact Centering issue
  client/src/pages/AboutUsPage/AboutUsPage.css
Labels: awaiting review

#217 Feature gallery dot service tag center
  client/src/components/ProjectImageGallery/ProjectImageGalleryAsante.js
  client/src/components/ProjectImageGallery/ProjectImageGalleryChimp.js
  client/src/components/ProjectImageGallery/ProjectImageGalleryEthiopia.js
  client/src/components/ProjectImageGallery/ProjectImageGalleryHaiti.js
  client/src/components/ProjectImageGallery/ProjectImageGallerySyria.js
  client/src/components/ProjectImageGallery/ProjectImageGalleryUnicef.js
  client/src/components/ServiceTag/ServiceTag.css
  client/src/pages/OurServicesPage/OurServicesPage.css
  client/src/pages/OurServicesPage/OurServicesPage.js
Labels: awaiting review

#223 updated header links to be bold and adjusted spacing and size
  client/src/components/NavBar/NavBar.css
Labels: awaiting review

#214 OurServicePage card alignment and card picture fix issue#197
  client/src/pages/OurServicesPage/OurServicesPage.css
  client/src/pages/OurServicesPage/OurServicesPage.js
Labels: awaiting review

#225 Fixed banner responsiveness
  client/src/pages/Home/Home.css
Labels: Quality Control, awaiting review

#227 AboutUsPage sizing issue
  client/src/pages/AboutUsPage/AboutUsPage.css
Labels: awaiting review

#230 ProjectSummaryPage
  client/src/components/ProjectCard/ProjectCard.css
  client/src/pages/ProjectSummary/ProjectSummary.css
  client/src/pages/ProjectSummary/ProjectSummary.js
Labels: awaiting review

#232 Backend documentation issue#218
  api/README.md
Labels: awaiting review, documentation

#234 Volunteers/ProjectSummary/WhoWeAreCard Updates
  client/src/components/WhoWeAreCard/WhoWeAreCard.js
  client/src/pages/ProjectSummary/ProjectSummary.css
  client/src/pages/ProjectSummary/ProjectSummary.js
  client/src/pages/VolunteersPage/VolunteersPage.css
Labels: awaiting review

#235 Updated details hex code
  client/src/pages/ProjectSummary/ProjectSummary.css
Labels: awaiting review

#236 removed space and button callback from ProjectCard
  client/src/components/ProjectCard/ProjectCard.js
Labels: awaiting review

#231 Frontend documentation alex hema
  client/README.md
Labels: awaiting review, documentation
