Repository statisticswithoutborders/swb-app, pull requests merged in 2020-08, with the labels that each got.

#43 Input :awaiting_review #17
  client/_templates/unnamed/new/css.ejs.t
  client/_templates/unnamed/new/stories.ejs.t
  client/_templates/unnamed/new/test.ejs.t
  client/_templates/unnamed/new/unnamed.ejs.t
  client/src/components/Input/Input.css
  client/src/components/Input/Input.js
  client/src/components/Input/Input.stories.js
  client/src/index.css
Labels: Atomic Component, awaiting review

#39 Feature fundingfact mv
  client/src/components/FundingFact/FundingFact.css
  client/src/components/FundingFact/FundingFact.js
  client/src/components/FundingFact/FundingFact.stories.js
  client/src/components/Input/Input.test.js
Labels: awaiting review

#38 Feature jeremiah button #13
  client/src/components/Button/Button.css
  client/src/components/Button/Button.js
  client/src/components/Button/Button.stories.js
Labels: awaiting review

#58 icons /new repo
  client/src/components/IconArrow/IconArrow.css
  client/src/components/IconArrow/IconArrow.js
  client/src/components/IconArrow/IconArrow.stories.js
  client/src/components/IconArrow/IconArrow.test.js
  client/src/components/IconArrow/arrow.png
  client/src/components/IconDownArrow/IconDownArrow.css
  client/src/components/IconDownArrow/IconDownArrow.js
  client/src/components/IconDownArrow/IconDownArrow.stories.js
  client/src/components/IconDownArrow/IconDownArrow.test.js
  client/src/components/IconImage/IconImage.css
  client/src/components/IconImage/IconImage.js
  client/src/components/IconImage/IconImage.stories.js
  client/src/components/IconImage/IconImage.test.js
  client/src/components/IconLogin/IconLogin.css
  client/src/components/IconLogin/IconLogin.js
  client/src/components/IconLogin/IconLogin.stories.js
  client/src/components/IconLogin/IconLogin.test.js
Labels: awaiting review

#60 copied over project card component
  client/src/components/ProjectCard/ProjectCard.css
  client/src/components/ProjectCard/ProjectCard.js
  client/src/components/ProjectCard/ProjectCard.stories.js
  client/src/components/ProjectCard/ProjectCard.test.js
Labels: awaiting review

#64 How it works mv
  client/src/assets/images/volunteers_path.png
  client/src/components/HowItWorks/HowItWorks.css
  client/src/components/HowItWorks/HowItWorks.js
  client/src/components/HowItWorks/HowItWorks.stories.js
  client/src/components/HowItWorks/HowItWorks.test.js
Labels: awaiting review

#63 Header/NavBar-MH
  client/src/components/NavBar/NavBar.css
  client/src/components/NavBar/NavBar.js
Labels: awaiting review

#61 new icon number
  client/src/components/IconLogin/IconLogin.css
  client/src/components/IconLogin/IconLogin.js
  client/src/components/IconLogin/IconLogin.stories.js
  client/src/components/IconLogin/IconLogin.test.js
  client/src/components/IconNumber/IconNumber.css
  client/src/components/IconNumber/IconNumber.js
  client/src/components/IconNumber/IconNumber.stories.js
  client/src/components/IconNumber/IconNumber.test.js
Labels: Atomic Component, awaiting review

#59 objective component /new
  client/src/components/Objective/Objective.css
  client/src/components/Objective/Objective.js
  client/src/components/Objective/Objective.stories.js
  client/src/components/Objective/Objective.test.js
Labels: awaiting review

#71 Who we are card mv
  client/src/components/WhoWeAreCard/WhoWeAreCard.css
  client/src/components/WhoWeAreCard/WhoWeAreCard.js
  client/src/components/WhoWeAreCard/WhoWeAreCard.stories.js
  client/src/components/WhoWeAreCard/WhoWeAreCard.test.js
  client/src/pages/ContactUsPage/ContactUsPage.css
  client/src/pages/ContactUsPage/ContactUsPage.js
  client/src/pages/ContactUsPage/ContactUsPage.stories.js
  client/src/pages/ContactUsPage/ContactUsPage.test.js
Labels: awaiting review

#75 Footer
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.js
  client/src/components/Footer/Footer.stories.js
  client/src/components/Footer/Footer.test.js
  client/src/components/IconImage/IconImage.css
  client/src/components/IconImage/IconImage.js
  client/src/components/IconImage/IconImage.stories.js
  client/src/components/Input/Input.js
Labels: awaiting review

#73 Blog card jh
  client/src/components/BlogCard/BlogCard.css
  client/src/components/BlogCard/BlogCard.js
  client/src/components/BlogCard/BlogCard.stories.js
  client/src/components/BlogCard/BlogCard.test.js
Labels: Molecular Component, awaiting review

#74 IconImage bug issue #69
  client/src/components/IconImage/IconImage.css
  client/src/components/IconImage/IconImage.js
Labels: awaiting review

#66 Fixed image issue Card component
  client/package-lock.json
  client/package.json
  client/src/components/Card/Card.css
  client/src/components/Card/Card.js
  client/src/components/Card/Card.stories.js
  client/src/components/Card/Card.test.js
Labels: awaiting review

#68 Feature form contact component
  client/.storybook/main.js
  client/src/components/Button/Button.js
  client/src/components/FormContact/FormContact.css
  client/src/components/FormContact/FormContact.js
  client/src/components/FormContact/FormContact.stories.js
  client/src/components/FormContact/FormContact.test.js
  client/src/components/Input/Input.css
  client/src/components/Input/Input.js
  client/src/components/Input/Input.stories.js
Labels: awaiting review

#65 added testimonial component
  client/src/components/Testimonial/Testimonial.css
  client/src/components/Testimonial/Testimonial.js
  client/src/components/Testimonial/Testimonial.stories.js
Labels: awaiting review

#72 ProjectPage with ProjectImageGalleries
  client/src/components/NavBar/NavBar.stories.js
  client/src/components/NavBar/NavBar.test.js
  client/src/components/ProjectImageGallery/ProjectImageGallery.css
  client/src/components/ProjectImageGallery/ProjectImageGallery.stories.js
  client/src/components/ProjectImageGallery/ProjectImageGallery.test.js
  client/src/components/ProjectImageGallery/ProjectImageGalleryAsante.js
  client/src/components/ProjectImageGallery/ProjectImageGalleryChimp.js
  client/src/components/ProjectImageGallery/ProjectImageGalleryEthiopia.js
  client/src/components/ProjectImageGallery/ProjectImageGalleryHaiti.js
  client/src/components/ProjectImageGallery/ProjectImageGallerySyria.js
  client/src/components/ProjectImageGallery/ProjectImageGalleryUnicef.js
  client/src/components/ProjectPage/ProjectPage.css
  client/src/components/ProjectPage/ProjectPage.stories.js
  client/src/components/ProjectPage/ProjectPage.test.js
  client/src/components/ProjectPage/ProjectPageAsante.js
  client/src/components/ProjectPage/ProjectPageChimp.js
  client/src/components/ProjectPage/ProjectPageEthiopia.js
  client/src/components/ProjectPage/ProjectPageHaiti.js
  client/src/components/ProjectPage/ProjectPageSyria.js
  client/src/components/ProjectPage/ProjectPageUnicef.js
  client/src/components/ServiceTag/ServiceTag.stories.js
Labels: awaiting review

#76 Projectsummary-AK issue #50
  client/package-lock.json
  client/package.json
  client/src/components/ProjectCard/ProjectCard.css
  client/src/components/ProjectCard/ProjectCard.js
  client/src/components/Video/Video.css
  client/src/components/Video/Video.js
  client/src/components/Video/Video.stories.js
  client/src/components/Video/Video.test.js
  client/src/pages/ProjectSummary/ProjectSummary.css
  client/src/pages/ProjectSummary/ProjectSummary.js
  client/src/pages/ProjectSummary/ProjectSummary.stories.js
  client/src/pages/ProjectSummary/ProjectSummary.test.js
Labels: awaiting review

#113 Feature service test twc
  client/src/components/Service/Service.test.js
Labels: awaiting review

#119 ProjectCard component responsiveness update.
  client/src/components/ProjectCard/ProjectCard.css
  client/src/components/ProjectCard/ProjectCard.stories.js
Labels: awaiting review

#115 How it works mv
  client/src/assets/images/volunteers_path.png
  client/src/components/HowItWorks/HowItWorks.css
  client/src/components/HowItWorks/HowItWorks.js
Labels: incomplete

#125 ProjectCard props update
  client/src/components/FundingFact/FundingFact.test.js
  client/src/components/ProjectCard/ProjectCard.js
  client/src/components/ProjectCard/ProjectCard.stories.js
Labels: awaiting review

#130 FormContact - Make responsive
  client/src/components/FormContact/FormContact.css
Labels: awaiting review

#128 Feature input test twc
  client/src/components/Input/Input.test.js
Labels: awaiting review

#131 tested testimonial component
  client/src/components/Testimonial/Testimonial.test.js
Labels: awaiting review

#134 WhoWeAreCard link prop update
  client/src/components/WhoWeAreCard/WhoWeAreCard.js
  client/src/components/WhoWeAreCard/WhoWeAreCard.stories.js
Labels: awaiting review

#133 FundingFact Tests issue #80
  client/src/components/FundingFact/FundingFact.test.js
  client/src/pages/ContactUsPage/ContactUsPage.css
  client/src/pages/ContactUsPage/ContactUsPage.js
  client/src/pages/VolunteersPage/VolunteersPage.css
  client/src/pages/VolunteersPage/VolunteersPage.js
  client/src/pages/VolunteersPage/VolunteersPage.stories.js
  client/src/pages/VolunteersPage/VolunteersPage.test.js
Labels: awaiting review

#116 our services page
  client/src/components/Card/Card.css
  client/src/components/NavBar/NavBar.css
  client/src/components/NavBar/NavBar.js
  client/src/components/Service/Service.css
  client/src/pages/OurServicesPage/OurServicesPage.css
  client/src/pages/OurServicesPage/OurServicesPage.js
  client/src/pages/OurServicesPage/OurServicesPage.stories.js
  client/src/pages/OurServicesPage/OurServicesPage.test.js
Labels: awaiting review

#111 Member card #34
  client/src/components/BlogCard/BlogCard.css
  client/src/components/BlogCard/BlogCard.js
  client/src/components/IconDownArrow/IconDownArrow.css
  client/src/components/IconDownArrow/IconDownArrow.js
  client/src/components/IconDownArrow/IconDownArrow.stories.js
  client/src/components/MemberCard/MemberCard.css
  client/src/components/MemberCard/MemberCard.js
  client/src/components/MemberCard/MemberCard.stories.js
  client/src/components/MemberCard/MemberCard.test.js
Labels: Atomic Component, awaiting review

#135 Feature form contact test twc
  client/src/components/FormContact/FormContact.test.js
Labels: awaiting review

#140 WhoWeAreCard test (issue #85)
  client/src/components/ProjectCard/ProjectCard.js
  client/src/components/WhoWeAreCard/WhoWeAreCard.test.js
Labels: awaiting review

#141 testimonial - added media queries
  client/src/components/Testimonial/Testimonial.css
Labels: awaiting review

#126 ContactUsPage update
  client/src/pages/ContactUsPage/ContactUsPage.css
  client/src/pages/ContactUsPage/ContactUsPage.js
Labels: Page Component, awaiting review

#143 IconImage tests (issue #93)
  client/src/components/IconImage/IconImage.test.js
Labels: awaiting review

#123 Project Model and Service Model for backend
  api/Pipfile
  api/Pipfile.lock
  api/api/__pycache__/__init__.cpython-38.pyc
  api/api/__pycache__/settings.cpython-38.pyc
  api/api/settings.py
  api/settings.sql
  api/swb/__init__.py
  api/swb/__pycache__/__init__.cpython-38.pyc
  api/swb/admin.py
  api/swb/apps.py
  api/swb/fixtures/swb.json
  api/swb/migrations/0001_initial.py
  api/swb/migrations/0002_auto_20200828_1444.py
  api/swb/migrations/0003_auto_20200828_1610.py
  api/swb/migrations/0004_auto_20200828_1610.py
  api/swb/migrations/0005_auto_20200831_1437.py
  api/swb/migrations/0006_member.py
  api/swb/migrations/0007_delete_member.py
  api/swb/migrations/__init__.py
  api/swb/models.py
  api/swb/tests.py
  api/swb/views.py
Labels: awaiting review

#148 Feature ServiceTag tests twc
  client/src/components/ServiceTag/ServiceTag.test.js
Labels: awaiting review

#149 MemberCard test (issue #107)
  client/src/components/MemberCard/MemberCard.test.js
Labels: awaiting review

#150 Member model w/seed
  api/swb/admin.py
  api/swb/fixtures/swb.json
  api/swb/migrations/0008_member.py
  api/swb/models.py
Labels: awaiting review

#156 App.js Routing, Header, and Footer #78
  client/src/App.js
  client/src/assets/images/Slice 1.png
  client/src/components/Card/Card.css
  client/src/components/Footer/Footer.js
  client/src/components/NavBar/NavBar.js
  client/src/pages/ContactUsPage/ContactUsPage.js
  client/src/pages/Home/Home.css
  client/src/pages/Home/Home.js
  client/src/pages/Home/Home.stories.js
  client/src/pages/Home/Home.test.js
  client/src/pages/OurServicesPage/OurServicesPage.js
Labels: incomplete

#77 Feature video ak Issue#50
  client/package-lock.json
  client/package.json
  client/src/components/Video/Video.css
  client/src/components/Video/Video.js
  client/src/components/Video/Video.stories.js
  client/src/pages/ProjectSummary/ProjectSummary.js
Labels: awaiting review

#157 ProjectCard tests (issue #88)
  client/src/components/ProjectCard/ProjectCard.test.js
  client/src/components/ProjectImageGallery/ProjectImageGallery.test.js
Labels: awaiting review

#155 Feature Card tests twc
  client/src/components/Card/Card.test.js
Labels: awaiting review

#159 Video test hema
  client/src/components/Video/Video.test.js
Labels: Testing, awaiting review

#160 Objective tests (issue #89)
  client/src/components/Objective/Objective.test.js
  client/src/pages/VolunteersPage/VolunteersPage.css
  client/src/pages/VolunteersPage/VolunteersPage.js
Labels: awaiting review

#147 Cardresponsiveness ak
  client/src/components/Card/Card.css
  client/src/components/Card/Card.js
  client/src/components/Card/Card.stories.js
Labels: awaiting review

#127 Aboutus
  client/src/components/Footer/Footer.css
  client/src/components/FundingFact/FundingFact.css
  client/src/components/IconDownArrow/IconDownArrow.css
  client/src/components/IconDownArrow/IconDownArrow.js
  client/src/components/IconDownArrow/IconDownArrow.stories.js
  client/src/components/IconNumber/IconNumber.js
  client/src/components/MemberCard/MemberCard.css
  client/src/components/MemberCard/MemberCard.js
  client/src/components/MemberCard/MemberCard.stories.js
  client/src/components/Objective/Objective.css
  client/src/pages/AboutUsPage/AboutUsPage.css
  client/src/pages/AboutUsPage/AboutUsPage.js
  client/src/pages/AboutUsPage/AboutUsPage.stories.js
  client/src/pages/AboutUsPage/AboutUsPage.test.js
  client/src/pages/OurServicesPage/OurServicesPage.css
  client/src/pages/OurServicesPage/OurServicesPage.test.js
Labels: Page Component, awaiting review

#110 HomePage #48
  client/src/pages/Home/Home.css
  client/src/pages/Home/Home.js
Labels: incomplete

#158 Form models w/no seed data
  api/swb/admin.py
  api/swb/migrations/0009_contact_newproject_volunteer.py
  api/swb/migrations/0010_auto_20200831_1922.py
  api/swb/migrations/0011_auto_20200831_1923.py
  api/swb/models.py
Labels: awaiting review
